
name: Build Tests
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Install actions/checkout@v2
      uses: actions/checkout@v2

    - name: Install actions/setup-python@v2 for ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Python build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        python -m pip install --upgrade setuptools pytest

    - name: python setup.py clean build
      run: |
        python setup.py clean build

    - name: python setup.py test
      run: |
        pytest

    - name: python setup.py install
      run: |
        python setup.py install

    - name: arpwitch --version
      run: |
        arpwitch --version
